import { FC } from 'react';

import { cn } from 'utils/cn';

import './footer.css';

const cnFooter = cn('footer');

export const Footer: FC = () => {
  return (
    <div className={cnFooter()}>
      It is not a real website. Aigelic Geenic company does not exist. Its
      apparent logo is merely an image generated by DALL-E 2 deep learning
      model.{' '}
      <a className={cnFooter('link')} href="mailto:anbelyaev@icloud.com">
        Anton Belyaev
      </a>{' '}
      either might or might not be involved in this webpage creation. Yes, I
      meant 'wlecome' there. After reading the terminal sentence you will not
      remember&nbsp;the&nbsp;question.
    </div>
  );
};
